"""create baseline tables

Revision ID: d708ba7fd472
Revises: 0002
Create Date: 2026-09-28 02:38:41.941255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd708ba7fd472'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_number', sa.Integer(), nullable=False),
    sa.Column('label_en', sa.String(length=40), nullable=False),
    sa.Column('label_hi', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_number')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('name_hi', sa.String(length=80), nullable=False),
    sa.Column('script', sa.String(length=40), nullable=False),
    sa.Column('is_tribal', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bhashini_supported', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_table('curriculum_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('name_hi', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['curriculum_grades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('total_pairs', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('license', sa.String(length=120), nullable=False),
    sa.Column('coverage_note', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=120), nullable=False),
    sa.Column('title_hi', sa.String(length=120), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['curriculum_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_language_id', sa.Integer(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('normalized_source', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('transliteration', sa.String(length=200), nullable=False),
    sa.Column('source_citation', sa.String(length=300), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('rights_cleared', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('rights_note', sa.String(length=300), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['curriculum_chapters.id'], ),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_text', 'target_language_id', name='uq_source_per_target_lang')
    )
    op.create_index('ix_translation_entries_normalized', 'translation_entries', ['normalized_source'], unique=False)
    op.create_table('translation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('source_language_code', sa.String(length=20), nullable=False),
    sa.Column('target_language_code', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('matched_entry_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_entry_id'], ['translation_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('page', sa.String(length=60), nullable=False),
    sa.Column('translation_history_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['translation_history_id'], ['translation_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('translation_history')
    op.drop_index('ix_translation_entries_normalized', table_name='translation_entries')
    op.drop_table('translation_entries')
    op.drop_table('curriculum_chapters')
    op.drop_table('dataset_metadata')
    op.drop_table('curriculum_subjects')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_table('curriculum_grades')
    # ### end Alembic commands ###